### PR TITLE
`delete_all` wrong number of arguments error on rails 5.1

### PR DESCRIPTION
**Pull request by assembler**
This little change will make SSO compatible with rails 5.1 while not breaking compatibility with rails4.

### CODE REVIEW

**Comment by born4new** [comment]
We ran into the same issue with Rails 5.1 when trying to log out.

**Comment by neckhair** [comment]
@adamcrown Any chance you can merge and release this soon?

**Comment by born4new** [comment]
Does anybody know if this project is still maintained?

**Comment by adamcrown** [comment]
Hi all. My apologies for taking so very long to get to this. The project is not abandoned but I'm not using it currently and am not working for Biola anymore either. So it's been hard for me to find the time to put into this. I should hopefully have more free time in the coming months and hope to do better in keeping up with issues and PRs.

Thanks for you help @assembler

**Comment by born4new** [comment]
@adamcrown Yay! Great news! Thanks!

Just so we know, are you planning a gem release soon?

**Comment by adamcrown** [comment]
Yep, just pushed 0.16.0. I'll try to keep up with PRs and new releases better in the future.

**Comment by neckhair** [comment]
@adamcrown Thanks!

**Pull request merged**
