### PR TITLE
Allow for explicit passing of 'config.rack_cas.fake = false' when set…

### PR DESCRIPTION
**Pull request by peterwells**
…ting up Rails environment.

Use case: culturally we set up three environments for each application dev, test, and prod. Attempted to get people to move away from using 'test' with regards to our Rails envrionments, but was met with silence. Would like to be able to use this gem as it has desired features over ruby-cas-client, but without being able to explicitly pass in a 'false' value for the fake flag we won't be able to.

### CODE REVIEW

**Comment by brandonrich** [comment]
+1 Biola folks, thanks for the gem.  This PR will let us use it going forward.  Please review and merge!

**Comment by peterwells** [comment]
Thanks @henryluki, I appreciate the feedback. This seems to be just a small, overlooked use case.

**Comment by mikestephens** [comment]
I will most definitely put testing this in our environment on my todo list. Hopefully I will be able to get to it soon as I am not as well versed in this gem as the original author. 

If @adamcrown wants to pop in and give his two cents I can expedite the process.

**Comment by adamcrown** [comment]
Sorry it took me so long to join in the conversation here.

This PR looks good to me. `fake` should have been in the `Configuration` class already, I must have just missed it somehow.

Thanks for the PR. @mikestephens, feel free to merge this anytime as far as I'm concerned.

This should also fix https://github.com/biola/rack-cas/issues/45.

**Comment by mikestephens** [comment]
Released in version 0.11.1

**Pull request merged**
