### PR TITLE
added attributes prefix option

### PR DESCRIPTION
**Pull request by dsusco**
This is a start for this issue: https://github.com/biola/rack-cas/issues/36

If you guys think it's enough I'll add some tests. Any thoughts on what it should do if the prefix create invalid XML or results in no nodes being found?

### CODE REVIEW

**Comment by adamcrown** [comment]
Thanks for taking a stab at this. It looks like a good start. I'd say go ahead and write the tests. As long as the default stays the same I don't see any harm in merging this as an option.

One quick note. I've never seen a different XML prefix for CAS responses in the wild so I'm not sure about this but should `cas:serviceResponse` and `cas:authenticationSuccess` also have the custom prefix?

**Comment by dsusco** [comment]
I couldn't say on the custom prefix, I also asked our CAS guy here and he was surprised to learn that there were name spaces on the tags to begin with. :P

When I was putting together the SAML validation response I ended up removing the namespaces all together:
https://github.com/biola/rack-cas/blob/c79ff02ffa6886189dc5a87b3019697400fc149e/lib/rack-cas/saml_validation_response.rb#L89

That actually might be a better way to solve this, but that's not a call I think I should make.

**Comment by adamcrown** [comment]
That's actually a good point. Removing the namespaces might simplify things. If you'd like to make a pull request for that some tests. I think I'd be happy to merge it. If not I'll see if I can get around to it in the future.

**Comment by dsusco** [comment]
OK, I reverted the first change and just removed the namespaces in the service validation response class. Did you want new tests? As the old ones still cover us.

**Comment by adamcrown** [comment]
Thanks. That looks good.

I think it would be good to have a test with a different namespace in the XML. Since that's the feature we're supporting with this PR, I'd want to make sure we don't break it in the future.

**Comment by dsusco** [comment]
Tests up. I used the original issue's xmlns for the namespaces.

**Comment by dsusco** [comment]
Are you all set with this Adam?

**Comment by dsusco** [comment]
Bump

**Comment by adamcrown** [comment]
Sorry. I've had a busy week. This looks good though. Thanks!

**Pull request merged**
