### PR TITLE
Rack 2.0 compatibility

### PR DESCRIPTION
**Pull request by neckhair**
Rack 2.0 changed the session storage api. Store, find and destroy methods were renamed.
see: rack/rack@4224c02

### CODE REVIEW

**Comment by adamcrown** [comment]
Thanks for working on this. Just let me know when you think it's ready.

**Comment by neckhair** [comment]
@adamcrown Seems to work now. The question is: Do you want to keep that compatibility workaround or  would it be better to do a major version bump and drop rack 1.x compatibility? I think the workaround is not too complicated to keep it like that.

**Comment by neckhair** [comment]
@adamcrown Any chance you can review this soon?

**Comment by adamcrown** [comment]
I apologize for being so behind on this. I'd like to dig into Rack 2.0 a bit and give it a proper review. I'm busy through the end of the month but I shouldn't have any trouble getting in merged and a new version released early May.

**Comment by neckhair** [comment]
@adamcrown OK, thanks!

**Comment by adamcrown** [comment]
Looks good. Thanks. I'll update the Mongoid session store as well and maybe get some other pull requests in and then release a new version.

**Comment by neckhair** [comment]
Cool, thanks!

**Comment by eriko** [comment]
Has there been a new release of the gem with this fix enabled for rails5/rack2 ?

**Comment by neckhair** [comment]
@adamcrown Do you mind releasing the Gem?

**Comment by adamcrown** [comment]
Sure. I just pushed up 0.14.0.

**Pull request merged**
