### PR TITLE
added saml validation and configuration option

### PR DESCRIPTION
**Pull request by dsusco**
We only pass attributes via SAML, so I added a new response class for SAML validation and a config option that let's you use it.

### CODE REVIEW

**Comment by adamcrown** [comment]
I apologize that I haven't been able to get to this for a while. I've recently move from the US to the Philippines and I still don't have reliable internet at home. So I'm having to survive off coffee shop Wi-Fi for a while.

This looks good but what CAS server are you using that uses this type of response?

Also, could you pleases add some tests for this new class? You should be able to just copy and tweak [this spec](https://github.com/biola/rack-cas/blob/master/spec/rack-cas/service_validation_response_spec.rb)

**Comment by dsusco** [comment]
We're using JASIG CAS 3.5.2. Apparently they broke off SAML support into the cas-server-support-saml module in 4.0, it was built in before that.

Added the tests. I also removed some unused error classes. I don't have any familiarity with SAML status codes (nor could I find where they're listed).

**Comment by adamcrown** [comment]
Looks like Travis CI turned up some errors with the tests. Could you take a look at those and get them passing?

**Comment by dsusco** [comment]
They're all coming from the ip-address method. Looks like the block is
returning nil. Just guessing, but maybe the job doesn't have access to that
information on the machine github runs it on?

Any idea for something more robust? I'll search around today. If I can't
find anything I guess I could add another option for the user to specify it.

**Comment by dsusco** [comment]
All set.

I was digging around in php-cas (which supports SAML). I don't think the IP is too critical. They're using a hard-coded  IP from some examples, so I just defaulted to the loopback.

**Comment by adamcrown** [comment]
Looks good. Thanks. I recently left Biola to pursue freelance work, so I don't have access to merge this commit but I'll get a hold of the right people who can.

**Comment by mikestephens** [comment]
Looks good to me too.

**Comment by mikestephens** [comment]
Added in version 0.11.0

**Comment by dsusco** [comment]
Thanks guys.

Out of curiosity, how are you using rack-cas in production? We're looking
at running apps via Passenger stand-alone behind an nginx server. The issue
I'm running into is Passenger is just passing localhost URLs for requests,
rack-cas then sends them to the CAS server, which, in turn, has no idea
what to do with them.


On Wed, Jun 3, 2015 at 12:09 PM, Michael Stephens <notifications@github.com>
wrote:

> Added in version 0.11.0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biola/rack-cas/pull/39#issuecomment-108504137>.
>



-- 
Dave

**Comment by adamcrown** [comment]
We started with regular Passenger and then moved to Puma. It sounds like you may need to set the `X-Forwarded-For`, `X-Forwarded-Host` and `X-Forwarded-Proto` headers.

**Comment by dsusco** [comment]
Thanks, that did it.

Figuring out the configuration for this app/environment has taken longer
than the actual programming...

On Tue, Jun 9, 2015 at 2:07 AM, Adam Crownoble <notifications@github.com>
wrote:

> We started with regular Passenger and then moved to Puma. It sounds like
> you may need to set the X-Forwarded-For, X-Forwarded-Host and
> X-Forwarded-Proto headers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biola/rack-cas/pull/39#issuecomment-110239065>.
>



-- 
Dave

**Pull request merged**
